### ISSUE TITLE
[feature] Export data additionally in xml format

### ISSUE THREAD

**Issue by Tungstwenty** [asksven/BetterBatteryStats#259]
Following up on [this comment](http://forum.xda-developers.com/showthread.php?p=29768318#post29768318), is it too early to have BBS writing all the data in a draft schema structure, in order to start collecting samples and drawing conclusions on what needs to be improved in the format so its analysis can be automated in the future?

**Comment by asksven** [comment]
JSON export looks lika a pretty good alternative to me
