### ISSUE TITLE
[bug] is hasSuRughts

### ISSUE THREAD

**Issue by asksven** [asksven/BetterBatteryStats#260]
08-23 23:08:20.657 W/System.err(10486): java.io.IOException: Error running exec(). Command: [su] Working Directory: null Environment: null
08-23 23:08:20.657 W/System.err(10486):     at java.lang.ProcessManager.exec(ProcessManager.java:211)
08-23 23:08:20.657 D/KeyguardViewMediator(  543): setHidden false
08-23 23:08:20.657 W/System.err(10486):     at java.lang.Runtime.exec(Runtime.java:168)
08-23 23:08:20.657 W/System.err(10486):     at java.lang.Runtime.exec(Runtime.java:241)
08-23 23:08:20.667 W/System.err(10486):     at java.lang.Runtime.exec(Runtime.java:184)
08-23 23:08:20.667 W/System.err(10486):     at com.asksven.andoid.common.contrib.Util.run(Util.java:80)
08-23 23:08:20.667 W/System.err(10486):     at com.asksven.andoid.common.contrib.Util.run(Util.java:65)
08-23 23:08:20.667 W/System.err(10486):     at com.asksven.android.common.kernelutils.RootDetection.hasSuRights(RootDetection.java:49)
08-23 23:08:20.667 W/System.err(10486):     at com.asksven.betterbatterystats.data.StatsProvider.writeDumpToFile(StatsProvider.java:1690)
08-23 23:08:20.667 W/System.err(10486):     at com.asksven.betterbatterystats.StatsActivity$WriteDumpFile.doInBackground(StatsActivity.java:741)
08-23 23:08:20.667 D/KeyguardViewMediator(  543): setHidden false
08-23 23:08:20.677 W/System.err(10486):     at android.os.AsyncTask$2.call(AsyncTask.java:264)
08-23 23:08:20.677 W/System.err(10486):     at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
08-23 23:08:20.677 W/System.err(10486):     at java.util.concurrent.FutureTask.run(FutureTask.java:137)
08-23 23:08:20.677 W/System.err(10486):     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:208)
08-23 23:08:20.677 W/System.err(10486):     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
08-23 23:08:20.677 W/System.err(10486):     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
08-23 23:08:20.677 W/System.err(10486):     at java.lang.Thread.run(Thread.java:856)
08-23 23:08:20.687 W/System.err(10486): Caused by: java.io.IOException: Permission denied
08-23 23:08:20.687 W/System.err(10486):     at java.lang.ProcessManager.exec(Native Method)
08-23 23:08:20.687 D/KeyguardViewMediator(  543): setHidden false
08-23 23:08:20.687 W/System.err(10486):     at java.lang.ProcessManager.exec(ProcessManager.java:209)
08-23 23:08:20.697 W/System.err(10486):     ... 15 more

**Comment by weifengteng** [comment]
My pad already rooted, but also prompt this error message
