### ISSUE TITLE
Asus Transformers have Two batteries

### ISSUE THREAD

**Issue by phedders** [asksven/BetterBatteryStats#335]
BBS looks awesome - but it gets quite confused by the Asus Transformer, which has a battery in the keyboard dock. BBS doesnt detect the second battery or the real state of charging because when docked (but not plugged in) it thinks the tablet is charging... which it is, but only from the dock. Confusing yes.

If you're interested in resolving this, please let me know how I can help debug it.

Thanks.

**Comment by asksven** [comment]
will not fix

**Comment by phedders** [comment]
Thanks for the consideration :)
