### ISSUE TITLE
[feature] save dump/logcat/dmesg each time the charger is plugged

### ISSUE THREAD

**Issue by albaldi** [asksven/BetterBatteryStats#413]
Yesterday, for unknown reason, my battery drop from 80% to 4% in some hour.
I promptly plugged the charger, but I lost the previous reference with the data, so I can't debug the problem.

This feature will help me alot.
thanks

**Comment by asksven** [comment]
After investigations I came to the conclusion that his feature can not be implemented: at the moment the device is plugged - and before BBS can run - all counters are reset so that the stats that get saved at this moment are pretty much zero
