### ISSUE TITLE
[bug] on some devices KWl shows a different number of entries at each refresh

### ISSUE THREAD

**Issue by asksven** [asksven/BetterBatteryStats#612]
http://forum.xda-developers.com/showthread.php?p=57166361

http://forum.xda-developers.com/showthread.php?p=57170379

**Comment by gaich** [comment]
Still cannot get KWL stats on Lollipop, even with other firmware (http://forum.xda-developers.com/lg-g3/development/rom-cloudyg3-1-0-t2917467), although the developer says the kernel is the stock LG kernel...
Logs: https://www.mediafire.com/?d2974959l80l097

**Comment by asksven** [comment]
I will have to look into this but as it is a local problem I can't hold back the release

**Comment by gaich** [comment]
Of course, it's just a specific LG case, maybe, I think it could be bump related.
http://forum.xda-developers.com/lg-g3/orig-development/bump-unlock-lg-g3-twrp-d852-d852g-f400-t2900614
Although everything was working with Kitkat.

**Comment by gaich** [comment]
George Tanner, GSAM Battery Monitor developer released an update today and he managed to display KWLs somehow for my device. As I said earlier, there wasn't this statistics for my device, now it's available in GSAM. Is it possible for you to contact him and ask, what did he implement for this?
![screenshot_2015-05-11-09-48-22](https://cloud.githubusercontent.com/assets/3396847/7557467/7d653982-f7c4-11e4-9d1e-3d15f0df7681.png)
![screenshot_2015-05-11-09-48-41](https://cloud.githubusercontent.com/assets/3396847/7557470/8a35d54a-f7c4-11e4-8430-ab6da43afa91.png)

**Comment by gaich** [comment]
That's what he answered: Yeah, LG in their infinite wisdom added a field to the kernel wakelock but never updated the parser in their code...so I get to parse it myself instead :)

**Comment by asksven** [comment]
that seems like a good clue. Can you please send me /system/kernel/debug/wakeup_sources as a file plus a dumpfile so that I have the device info to check on for using a special parser. I will change the format and can use the file to test. Unfortunately as we don't have any sources from LG I will have to implement the alternate handling only for one specific kernel version/device/brand

**Comment by asksven** [comment]
I meant /sys/kernel/debug/wakeup_sources

**Comment by gaich** [comment]
http://www.mediafire.com/download/ubc9ca312a92uaz/Documents.zip
