### ISSUE TITLE
[feature] Please add GPS usage stats

### ISSUE THREAD

**Issue by gaich** [asksven/BetterBatteryStats#677]
Is it possible to add GPS usage stats tab to the programm and dump as well, just similar to Network stats we have now? 
It would be great to detect whether some aps were using GPS or were sending location requests. Of course, if this data can be read from some system files.

**Comment by qwerty22** [comment]
It would be useful!
This information is available from "Location" menu "App Ops Xposed" and "Recent Location Requests" (during the last 15 minutes) main menu Android. However, there is no possibility to correlate the data with BetterBatteryStats.
