### ISSUE TITLE
[bug] dumpsys alarm does not deliver any results when called with su but does when run as user 

### ISSUE THREAD

**Issue by asksven** [asksven/BetterBatteryStats#703]

**Comment by d8389** [comment]
Patched & 100% working version on Samsung  5.x TW ROM only (may not work on another devices)
To install:
Remove official version.
Copy the file into /system/priv-app
Set permissions 644
Reboot.

https://my.pcloud.com/publink/show?code=XZuozVZKClInjJYKrjUSP0ATK2lN7UOz80y

**Comment by asksven** [comment]
Won't fix: this behavior is not normal to android, use API mode instead

**Comment by qwerty22** [comment]
"Accessing Alarms in API mode as dumpsys has failed"
