### ISSUE TITLE
Installing companion system app removes normal app. Impossible to undo, update or uninstall.

### ISSUE THREAD

**Issue by Evi1M4chine** [asksven/BetterBatteryStats#706]
This is a real bad one.

When enabling that root companion app thing, the main app exits abruptly. Then, there are two BetterBatteryStats icons in the app list. Starting the first shows a screen, saying that it’s a companion app that does nothing, and indeed it has no menus or anything. The second one just gives me a dialog, saying that it isn’t installed.

FDroid *now* also shows me there’s an update from 1.0.0.0 to 1.15.0.0 available.

But since it is a system app now, it can neither be uninstalled nor updated (due to supposedly being signed with a different key [WAT?]). Attempting to uninstall it, just results in an error with – of course – no reason given whatsoever.

And since the normal app is “gone”, I can’t undo the move to /system either.

Now what do I do?

This is probably the worst case scenario of a bug, apart from maybe deleting all data. ;)

Edit: For now, I have disabled the app, and will try “Wakelock detector” instead…

**Comment by asksven** [comment]
After installing the system app a reboot is required. On some devices the reboot is known to remove the main app but it can be re-installed afterward. 
The bbs version from fdroid is a kang so it is logical that an attempt to update will fail.

**Comment by Evi1M4chine** [comment]
What in the world is a “kang”?? Also, what do you mean with “bbs version”?
And /obviously/ the update came from F-Droid too!

I did a reboot. The main app can /not/ be reinstalled after it. That’s the point.

I flashed an updated Cyanogenmod, and finally I could remove it. I will never install this crap again, or anything else made by you.

I’m really disappointed at how little of a shit you seem to give about support, that you would talk literally nonsense and make up non-existing words, and clearly have not read, let alone fully understood half my comment. … How much weed do you smoke a day??

**Comment by asksven** [comment]
kang = unapproved copy not endorsed nor supported by me, in other words I have not built and do not maintain that version. 
BTW the tone sets the music and based on your feedback you are more interested in insulting me that to fix the issue so have a good day.

**Comment by Evi1M4chine** [comment]
Yeah, go blame the messenger. You’re the one who caused the shit that made the anger, so boo-hoo.
You’re probably one of those who hurt someone, and then criticise him for being so loud with his crying…

And how convenient, to blame it on those who changed nothing but circumvent your little crime scheme. (Software is not a product. The *work* of software development is a product. And *only* that work. Not sitting on your [by definition] criminal artificial scarcity and demanding money or advertisement or similar bullshit for letting people make copies, while yourself doing no work whatsoever. On top of the fact that having control over information while passing it on to everyone is not only a self-contradiction, but literally physically impossible.)

At least now I know where your bubble of ignorance comes from.
