### ISSUE TITLE
[feature] add permissions without system app

### ISSUE THREAD

**Issue by DavisNT** [asksven/BetterBatteryStats#716]
At least on some Android version (e.g. Android 5.1 Lollipop) it is possile to grant necesarry `BATTERY_STATS` and `DUMP` permissions to Better Battery Stats by invoking the following commands as root (without installing system app):

    pm grant com.asksven.betterbatterystats android.permission.BATTERY_STATS
    pm grant com.asksven.betterbatterystats android.permission.DUMP

I suggest leaving system app as last resort (it is possible that it is not needed at all - I have **not** tested these command lines on all affected Android versions). I suggest invoking these commands as root and **restarting Better Battery Stats process** before offering to install the system app. Process can be restarted by setting up `AlarmManager` alarm and doing `System.exit(0);`.

**Comment by asksven** [comment]
I will implement that as an experimental feature but as long as we don't have more experience with all builds/flavours the system app will stay the supported way to gain those stats.

**Comment by DavisNT** [comment]
Is granting only `BATTERY_STATS` (and **not** `DUMP`) permission enough? 
And will process restart be covered?

**Comment by asksven** [comment]
A few first tests show that the permission that was set at starting the app survives a reboot so it seems to get persisted properly. I will play with DUMP today as I have noticed inconsistencies with that perm anyway (when set it should not require su to do dumpsys but it does). As noted in the change log this feature is experimental anyway so it will require some testing.

**Comment by DavisNT** [comment]
With "process restart" I meant restarting Better Battery Stats after granting permission this way (most likely permissions granted this way become effective **only on next start of the application**). 
There shouldn't be any issues caused by reboot of the phone/tablet.

A bit more info on granting permissions to BBS by `pm grant` is on XDA thread: http://forum.xda-developers.com/apps/betterbatterystats/alternative-to-installing-battery-stats-t3189333

**Comment by asksven** [comment]
I don't really see what you are getting at. I've tested the current implementation positively so I don't see anything to fix

**Comment by DavisNT** [comment]
Have you performed test cases like this on different versions of Android?
1. Uninstall BBS (including system app)
2. Install and run BBS
3. Ensure that "Install as System App" screen is not shown
4. Ensure that data collection starts right away (and not on some later/"random" moment when BBS process actually gets restarted due to Android memory management or phone reboot)

As I previously stressed - at least some permissions (i.e. `READ_LOGS`) on some versions of Android are requiring restart of the application package process after being granted by `pm grant`. Have you tested that permissions required by BBS do not require process restart (to actually work) on any supported version of Android (5.x and 6.0 - see XDA thread on why not 4.4)?

**Comment by asksven** [comment]
I did a simple test with the debugger to find out when the perm was set and when it was visible to the app. As this is an experimental feature it will be up the community to do extensive testing and give feedback.
