### ISSUE TITLE
[feature] option to select destination path tasker plugin

### ISSUE THREAD

**Issue by rejhgadellaa** [asksven/BetterBatteryStats#753]
I've asked for a json export option for the tasker integration a while ago - which you've implemented so that's awesome! - but I was wondering if it is also possible to specify a destination folder. As far as i know it always writes the files in the root but i want the files to be uploaded automatically and i think this would be a nice way to do that?

Thanks!

**Comment by asksven** [comment]
In the advanced settings you will find an option to write dumpfiles to the private storage. Isn't that what you are looking for?

**Comment by rejhgadellaa** [comment]
But other apps can't access the private storage, right?

Here's what I want (I was on my phone this morning so I had some trouble typing out the full thing :))
- Have tasker export a json dump every day at [x]:[xx]
- Use another tasker plugin like FolderSync (https://goo.gl/0zSrTf) to automatically upload that file to google drive

So I basically need BBS to write the json to a folder where FolderSync or a similar plugin has access

**Comment by asksven** [comment]
Got it!
I did some research and found a neat file picker so I will do some tests and seee if it also allows to pick directories. Once I found a solution I will implement an alternate free selectable place for storing data.

**Comment by rejhgadellaa** [comment]
Awesome! Thanks for responding and acting on it so fast!
