### ISSUE TITLE
getBluetoothInStateTime not found

### ISSUE THREAD

**Issue by ishratkhan** [asksven/BetterBatteryStats#754]
I am not able to find method getBluetoothInStateTime inside BatteryStatsProxy.java,
Please help

**Comment by asksven** [comment]
That is because I have not committed android common yet. Is it urgent?

**Comment by ishratkhan** [comment]
Yes, It is urgent, Please commit, that would help me a lot.

Thank you

**Comment by asksven** [comment]
pushed
