### ISSUE TITLE
[bug]Can't upgrade 1.0.0.0 to 1.15.0.0 version

### ISSUE THREAD

**Issue by siva-epari** [asksven/BetterBatteryStats#758]
When i press "Upgrade", it says: "The new version is signed with a different key to the old one. To install the new version, the old one must be uninstalled first. Please do this and try again"

When i uninstall, it says: "Uninstall error: Failed to uninstall due to an unknown error"

**Comment by asksven** [comment]
please provide source and target signatures. I have not changed my debug keys since the first ever published version so maybe you have obtained bbs from another source
