### ISSUE TITLE
not working in touchwiz 6.0.1

### ISSUE THREAD

**Issue by chrcoluk** [asksven/BetterBatteryStats#771]
Hi

even installed as system app the following 3 stats do not work.

Kernel wakelocks - always says no data
Partial wakelocks - always says no data
Alarms - says needs battery_stat permission

It works on CM13 but not on touchwiz marshmallow.  It worked fine for me on kitkat touchwiz.

Phone is rooted with xposed.

**Comment by asksven** [comment]
can you please provide a logcat with debug on (advanced prefs I have bbs)?

**Comment by chrcoluk** [comment]
An update, the version of XDA forums works fine, this bug was filed based on the playstore version.

If you still want this logcat I will do it for you.

**Comment by asksven** [comment]
yes I'd be interested in knowing what the problem was as I have not consciously fixed anything in that regards

**Comment by asksven** [comment]
No further feedback: can not reproduce
