### ISSUE TITLE
Unable to build application

### ISSUE THREAD

**Issue by RalfJung** [asksven/BetterBatteryStats#784]
I am trying to build this application from source. However, due to a pretty complete lack of documentation, I have not been able to do this so far.

What I did so far: I cloned this repo, AndroidCommon and ckChangeLog into a common folder (because this repo kept complaining about those folders being missing). However if I do `ant release` in `BetterBatteryStats` in this repo, it complains
```
/home/r/bin/android-sdk/tools/ant/build.xml:573: ../../ckChangeLog/ckChangeLog/src/main resolve to a path with no project.properties file for project /home/r/src/android/BetterBatteryStats/BetterBatteryStats/BetterBatteryStats
```
However, trying to build `ckChangeLog` also fails. I am doing `./gradlew assemble`, and the result is
```
> No such property: nexusUsername for class: org.gradle.api.publication.maven.internal.ant.DefaultGroovyMavenDeployer
```
Is it even possible to build this application with the publicly available sources?

**Comment by asksven** [comment]
What toolchain are you using? Bbs is still on Eclipse but I am planning to move to AS in the next release.

**Comment by RalfJung** [comment]
I installed `ant` from the distribution packages and used the grade wrapper shipped with `ckChangeLog` (becuase the version of gradle that I have installed is too new, it seems). Of course I also have the Android SDK installed.

Not sure if that answers your question, but that's all I got in terms of toolchains. I'm not an Android developer myself, so I don't have any Android IDEs installed. Gradle and ant were enough to compile the android apps that I attempted to build so far, without any trouble.

**Comment by asksven** [comment]
I have started moving my toolchain to android studio and you will find a better support in the future

**Comment by asksven** [comment]
if you want to give it a swing branch master-androidstudio is up

**Comment by RalfJung** [comment]
Thanks a lot, I was now able to use gradle to build the latest version of the app :)
