### ISSUE TITLE
The application can not be started!

### ISSUE THREAD

**Issue by AStasenko** [asksven/BetterBatteryStats#795]
BBS v2.2.2.0
Phone HUAWEI HONOR 7 (PLK-L01C10B331, Android 6.0 Marshmallow, EmUI 4.0.2, Rooted)
Installation of the application is normal.
But when I run the application, for about a minute I see an empty white screen, then the banner "Calculation ..." appears on the screen and hangs endlessly.
I can exit from this only by killing the process in task killer

`android.permission.BLUETOOTH
android.permission.WAKE_LOCK
android.permission.GET_TASKS
android.permission.ACCESS_NETWORK_STATE
android.permission.BATTERY_STATS
android.permission.READ_EXTERNAL_STORAGE
android.permission.ACCESS.SUPERUSER
android.permission.RECEIVE_BOOT_COMPLETED
android.permission.DEVICE_POWER
android.permission.ACCESS_WIFI_STATE
android.permission.WRITE_EXTERNAL_STORAGE
android.permission.READ_PHONE_STATE
android.permission.DUMP
android.permission.READ_LOGS`

**Comment by gaich** [comment]
There were some examples of such behaviour, [i.e.](https://forum.xda-developers.com/showpost.php?p=58629731&postcount=27522). The same things happen in Russian forum as well, I cannot find what`s wrong. The phones are rooted, the 14 permissions are granted, including batterystats. All seems to be OK, but the problem remains unsolved. @asksven , are there any ideas?

**Comment by AStasenko** [comment]
![9893508](https://cloud.githubusercontent.com/assets/26482989/24043628/957965c4-0b28-11e7-9608-acd2e6235a6d.jpg)
[aLogCat_BBS.txt](https://github.com/asksven/BetterBatteryStats/files/850546/aLogCat_BBS.txt)

**Comment by AStasenko** [comment]
[aLogCat_BBS.txt](https://github.com/asksven/BetterBatteryStats/files/850549/aLogCat_BBS.txt)

**Comment by asksven** [comment]
Have you tried without root and granting the perms with adb? I have seen such behaviors when root is broken and causing huge waits when issuing a root command

**Comment by AStasenko** [comment]
1. BBS application does not even request Root access. This can be seen in the SuperSU logs
2. Root on my phone is correct. This is confirmed by RootChecker. SD Majd, LakiPatcher and Root Explorer works correctly and are fully functional.
3. For the sake of using BBS, I will not disable root access. It is necessary for the operation of other applications. It's easier to find another application to monitor power consumption.
