### ISSUE TITLE
Privacy policy page not accessible (password protected?)

### ISSUE THREAD

**Issue by cris-** [asksven/BetterBatteryStats#815]
Hi

the privacy policy link specified on the Play Store redirects to a password protected page:

![image](https://user-images.githubusercontent.com/6074010/32265293-b3789824-bee2-11e7-91ef-e9dcf961a43b.png)

It would be nice to have that page freely available.

Thank you in advance for your help.

P.S.: I'm a "paying user" of the pro version ;-)

**Comment by asksven** [comment]
fixed
