### ISSUE TITLE
Plugin not showing up in Tasker

### ISSUE THREAD

**Issue by rojaxthegreat** [asksven/BetterBatteryStats#825]
Was looking to setup automated json dumps and analyze within tasker and found that BBS plugin appears to be missing.  
BBS 2.3-217
Tasker 5.1
Android 8.0

**Comment by asksven** [comment]
Looks like I have broken something in the way BBS is exposed to tasker. I guess that happened when I moved to android studio. Will look into it

**Comment by rojaxthegreat** [comment]
Thanks a bunch man, really appreciate your work and app
