### ISSUE TITLE
Please tag releases

### ISSUE THREAD

**Issue by IzzySoft** [asksven/BetterBatteryStats#859]
Hi Sven, could you please tag at least the most recent release (and then continue tagging new releases)? Tags stopped at v2.3RC/87, while HEAD has 2.5/95. Without tags, [updates on F-Droid are stuck](https://gitlab.com/fdroid/fdroiddata/issues/868).

Thanks in advance!

**Comment by IzzySoft** [comment]
@asksven an chance?

**Comment by asksven** [comment]
I have moved to branches instead of tags a while ago

**Comment by IzzySoft** [comment]
That unfortunately leaves updates with F-Droid stuck, as there's no way to automatically detect new versions then. F-Droid can only work with branches pointed to by a tag (or when the commit hash was set manually in the build block).

Further, how to determine what to build as it is now? Do you create a new branch when a new version (corresponding to the branch name) is ready – or when you start working on it?
