### ISSUE TITLE
Dark theme not working

### ISSUE THREAD

**Issue by OswaldBoelcke** [asksven/BetterBatteryStats#879]
This ticket is in reference to my post [here](https://forum.xda-developers.com/t/app-2-2-05-oct-v2-4-betterbatterystats.1179809/post-85114647) on XDA.

BBS v2.6 from F-Droid.
Device: Samsung Galaxy S8+ (SM-G955F), LOS 16.0 rooted, Magisk v23.0, EdXposed, root and all required permissions granted to BBS, access to data usage granted.

Issue: When switching in Advanced Settings to the dark theme BBS always stays on the light theme.

Attached logcat taken during attempts to switch the theme. Please advise if further information is required.
[2021-06-01-12-58-13.txt](https://github.com/asksven/BetterBatteryStats/files/6575822/2021-06-01-12-58-13.txt)
![Screenshot_20210601-125839_BBS](https://user-images.githubusercontent.com/21972717/120314962-5a0ec880-c2cb-11eb-9dc0-b181ec547055.png)
![Screenshot_20210601-125851_BBS](https://user-images.githubusercontent.com/21972717/120314965-5aa75f00-c2cb-11eb-95b0-79e8cf357a8c.png)
![Screenshot_20210601-125858_BBS](https://user-images.githubusercontent.com/21972717/120314967-5b3ff580-c2cb-11eb-9410-7f8a63c85fd5.png)
![Screenshot_20210601-125907_BBS](https://user-images.githubusercontent.com/21972717/120314970-5bd88c00-c2cb-11eb-8e05-52cb595984a5.png)

**Comment by atonement87** [comment]
I am facing the same issue in the latest 2.6 build.

**Comment by jswinde** [comment]
I just installed the latest version and noticed the same.

**Comment by asksven** [comment]
I am not the maintainer of the app distributed on f-droid
