### ISSUE TITLE
[Enhancement] Integrate Shizuku app for adb permissions

### ISSUE THREAD

**Issue by shom13** [asksven/BetterBatteryStats#886]
Please integrate shizuku into your app so that users dont need to grant the permissions manually through adb, instead will be done via shizuku app.

**Comment by asksven** [comment]
I don't get your point. If your phone is rooted BBS takes care of everything, if your phone is not rooted there are no ways around running adb AFAIK

**Comment by mirh** [comment]
You are missing a part of the puzzle then. 
https://www.androidpolice.com/how-to-use-shizuku-for-adb-rootless-mods-on-any-android-device/

**Comment by jstetten** [comment]
Granting permissions is the #1 use of Shizuku for the majority of apps. Any chance of taking another look at this, @asksven? Cheers.
