### ISSUE TITLE
Seems that the wrong battery percentage shown in BBS

### ISSUE THREAD

**Issue by bigjoncoop** [asksven/BetterBatteryStats#887]
I'm new to using BBS.

But when you first open the app on the very top it displays:

10m 43s / Batt.: -2% [12.6%/h]

Am I assuming correctly that the -2% is showing the total battery percentage?

![Screenshot_20220428-222621](https://user-images.githubusercontent.com/59851211/165881504-41b2b557-961d-4435-bf2a-b471cf0c70e4.jpg)

**Comment by asksven** [comment]
-2% means your phone as lost 2% in the last 5 minutes
