### ISSUE TITLE
granting `hidden_api_policy` does not work on nokia 8.3 5g

### ISSUE THREAD

**Issue by leaumar** [asksven/BetterBatteryStats#896]
Hi 🙂 Please advise:

![Screenshot_20220712-232828](https://user-images.githubusercontent.com/3950300/178598856-06c72867-f456-4d05-94aa-da47ba06eac7.png)

![image](https://user-images.githubusercontent.com/3950300/178598881-807f51ee-f6fa-4e53-bfc4-a91c0d894311.png)

My phone is a nokia 8.3 5g updated to android 12 (and boy, what a ****show android 12 has turned out to be for me)

I'm running Version 3.0-beta-2-469 (100)

Do you need any other information from me to troubleshoot this?

**Comment by elhennig** [comment]
Same here on Android 12 with Samsung Galaxy A52 on version 3.0-beta-3-482 (101)

The command works but the setting is not persistent

**Comment by elhennig** [comment]
I tried ending the app, removing all data and start from scratch. This seemed to have worked. And it is still working after a reboot ;-)

**Comment by leaumar** [comment]
Just downloaded the latest release and redid it, it works here too now, thanks @elhennig
