### ISSUE TITLE
Add screenshots of the application

### ISSUE THREAD

**Issue by jcperil** [asksven/BetterBatteryStats#909]
Please add screenshots for F-Droid. I think it is only fair that the users know about the interface before installing.

**Comment by asksven** [comment]
I am not the maintainer of the F-Droid distribution not has it been discussed / agreed by me, even if I am named there

**Comment by asksven** [comment]
I am sorry but I am not the maintainer of the F-Droid entry and this entry was added without my consent. If you want to stay current on BBS development I recommend google play of XDA since I maintain these sources

Best regards
Sven
