### ISSUE TITLE
App cannot be removed 

### ISSUE THREAD

**Issue by ZetaMap** [asksven/BetterBatteryStats#918]
the app cannot be uninstalled, by any ways.  I tried to uninstall with play store, f-droid, Lucky patcher, Titanium Backup, by hack recovery, by deleting the files manually, by purging all the files of the system concerning the application.  And each time it comes back.

**Comment by asksven** [comment]
it is not clear to me how you installed the app so I can not help. And appstore install and normal uninstall has aleways done the trick for me. If you have installed the app as a system app please follow the instructions for uninstalling from the source (that is not mw)

**Comment by ZetaMap** [comment]
I installed it with f-droid with privilege extension (to install app with root, not with package installer of android). And when I wanted to uninstall it, it placed itself in system application mode necessary for Android in the /system/priv-app folder, and in a cache, probably the cache-dalvik.  anyway when i searched the whole system for the name of apk, i found it in lots of config file

**Comment by asksven** [comment]
Unfortunately I am not the maintainer of the F-Droid entry for BBS and I do not control the build process or the docs since the entry on F-Droid has been made without consulting me / without my consent. I am afraid I can not help you
